Snitz.PostThanks/ViewModels/PostThanksViewModel.cs
namespace PostThanks.Models
{
    public class PostThanksViewModel
    {
        public int UserId { get; set; }
        public int TopicId { get; set; }
        public int ReplyId { get; set; }
        public bool PostAuthor { get; set; }
        public bool Thanked { get; set; }
        public bool ShowCount { get; set; }
        public bool Showlink { get; set; }
        public int ThanksCount { get; set; }

        public bool IsArchived { get; set; } = false;
    }

    public class PostThanksProfile
    {
        public int Received { get; set; }
        public int Given { get; set; }
    }
}

Snitz.PostThanks/Controllers/PostThanksController.cs
using BbCodeFormatter;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using PostThanks.Models;
using Snitz.PostThanks.Models;
using SnitzCore.Data;
using SnitzCore.Data.Interfaces;
using SnitzCore.Data.Models;

namespace Snitz.PostThanks.Controllers
{
    public class PostThanksController : Controller
    {
        private readonly ISnitzConfig _config;
        private readonly PostThanksContext _context;
        private readonly ICodeProcessor _bbCodeProcessor;
        private readonly IMember _memberService;
        private readonly string? _tableprefix;
        private readonly SnitzDbContext _snitzContext;
        private readonly PostThanksRepository thanksRepository;
        
        public PostThanksController(ISnitzConfig config,PostThanksContext dbContext,ICodeProcessor BbCodeProcessor,
            IMember memberService,IOptions<SnitzForums> options,SnitzDbContext snitzContext)
        {
            _config = config;
            _context = dbContext;
            _bbCodeProcessor = BbCodeProcessor;
            _memberService = memberService;
            _tableprefix = options.Value.forumTablePrefix;
            _snitzContext = snitzContext;
            thanksRepository = new PostThanksRepository(_context,_config,_snitzContext,options,memberService);
        }

        /// <summary>
        /// Renders a partial view displaying the "Thanks" icon for a specific topic or reply.
        /// </summary>
        /// <param name="id">The unique identifier of the topic to display the "Thanks" section for.</param>
        /// <param name="replyid">The unique identifier of the reply within the topic. Defaults to <see langword="0"/> if not specified.</param>
        /// <param name="showcount">A value indicating whether the count of "Thanks" should be displayed. Defaults to <see langword="false"/>.</param>
        /// <param name="showlink">A value indicating whether the "Thanks" link should be displayed. Defaults to <see langword="true"/>.</param>
        /// <returns>A partial view containing the "Thanks" section for the specified topic or reply.</returns>
        public ActionResult Index(int id, int replyid = 0, bool showcount = false, bool showlink = true)
        {
                var vm = new PostThanksViewModel
                {
                    UserId = _memberService.Current().Id,
                    TopicId = id,
                    ReplyId = replyid,
                    Thanked = false,
                    ShowCount = showcount,
                    Showlink = showlink
                };
                vm.Thanked = thanksRepository.IsThanked(id, replyid,_memberService.Current()?.Id);
                vm.ThanksCount = thanksRepository.Count(id, replyid);
                //vm.PostAuthor = thanksRepository.IsAuthor(id, replyid);

                return PartialView("_Thanks", vm);

        }

        /// <summary>
        /// Records a "thank you" action for a specific reply in a discussion thread.
        /// </summary>
        /// <remarks>This action requires authorization. The method adds a "thank you" entry for the
        /// specified reply and returns a JSON object with the result of the operation.</remarks>
        /// <param name="id">The identifier of the discussion thread.</param>
        /// <param name="replyid">The identifier of the reply being thanked.</param>
        /// <returns>A JSON result indicating the operation's success or failure.</returns>
        [Authorize]
        public IActionResult Thank(int id, int replyid /*, string returnUrl*/)
        {
            thanksRepository.AddThanks(id, replyid);

            return Json(new { result = "OK", error = "" });

        }

        /// <summary>
        /// Retrieves a list of members who have "thanked" the post and renders a partial view.
        /// </summary>
        /// <param name="id">The identifier of the primary entity for which members are retrieved.</param>
        /// <param name="replyid">The identifier of the reply or related entity used to filter the members.</param>
        /// <returns>A <see cref="PartialViewResult"/> that renders the "_Members" partial view with the retrieved members.</returns>
        public PartialViewResult Members(int id, int replyid)
        {
                var members = thanksRepository.Members(id, replyid);
                return PartialView("_Members", members);

        }

        /// <summary>
        /// Removes a "thank" reaction associated with a specific reply.
        /// </summary>
        /// <param name="id">The unique identifier of the user who gave the "thank".</param>
        /// <param name="replyid">The unique identifier of the reply from which the "thank" is being removed.</param>
        /// <returns>An <see cref="IActionResult"/> containing a JSON object with the result of the operation. The result will
        /// indicate success or failure.</returns>
        public IActionResult UnThank(int id, int replyid/*, string returnUrl = ""*/)
        {
            thanksRepository.DeleteThanks(id, replyid);
            return Json(new { result = "OK", error = "" });

        }

        #region Admin
        /// <summary>
        /// Updates the "Allow Thanks" setting for a specific forum based on the provided parameters.
        /// </summary>
        /// <remarks>If an error occurs during the update process, the method sets error details in the
        /// <see cref="ViewBag"/>  and returns an error view.</remarks>
        /// <param name="id">The unique identifier of the forum whose setting is being updated.</param>
        /// <param name="check">A string representing the desired state of the "Allow Thanks" setting.  Use "true" to enable the setting or
        /// any other value to disable it.</param>
        /// <returns>An empty result indicating the operation has completed.</returns>
        public IActionResult ForumSettings(int id, string check)
        {
            try
            {
                thanksRepository.SetAllowThanks(id, check == "true" ? 1 : 0);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Problem updating F_ALLOWTHANKS in Forum";
                ViewBag.ErrTitle = "Error: Thanks";
                return View("_Error");
            }

            return new EmptyResult();
        }
        #endregion

        #region Profile
        /// <summary>
        /// Returns a partial view displaying the "Thanks" profile for a specified member.
        /// </summary>
        /// <remarks>The view model includes the count of "Thanks" received and given by the specified
        /// member.</remarks>
        /// <param name="id">The unique identifier of the member whose "Thanks" profile is to be retrieved.</param>
        /// <returns>A <see cref="PartialViewResult"/> containing the "_Profile" partial view and the associated view model.</returns>
        public PartialViewResult ThanksProfile(int id)
        {
            var vm = new PostThanksProfile
            {
                Received = thanksRepository.MemberCountReceived(id),
                Given = thanksRepository.MemberCountGiven(id)
            };


            return PartialView("_Profile", vm);

        }

        #endregion

    }
}

Snitz.PostThanks/ViewComponents/PostThanksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using PostThanks.Models;
using Snitz.PostThanks.Models;
using SnitzCore.Data;
using SnitzCore.Data.Interfaces;
using SnitzCore.Data.Models;

namespace Snitz.PostThanks.ViewComponents
{
    /// <summary>
    /// Represents a view component for rendering various templates related to the "Post Thanks" feature in the forum.
    /// </summary>
    /// <remarks>This view component supports multiple templates, including forum configuration, topic
    /// summaries, user profiles,  and administrative views. It interacts with the database and other services to
    /// retrieve and display data  relevant to the "Post Thanks" functionality.</remarks>
    public class PostThanksViewComponent : ViewComponent
    {
        private readonly SnitzDbContext _dbContext;
        private readonly ISnitzConfig _config;
        private readonly PostThanksContext _thanksContext;
        private readonly PostThanksRepository thanksRepository;
        private readonly IMember _memberService;

        public PostThanksViewComponent(SnitzDbContext dbContext, ISnitzConfig config,PostThanksContext thanksContext,IOptions<SnitzForums> options,IMember memberService)
        {
            _dbContext = dbContext;
            _config = config;
            _thanksContext = thanksContext;
            thanksRepository = new PostThanksRepository(thanksContext,_config,dbContext,options, memberService);
            _memberService = memberService;
        }

        /// <summary>
        /// Asynchronously invokes the specified view component template with the provided parameters.
        /// </summary>
        /// <remarks>The behavior of this method depends on the specified <paramref name="template">:
        /// <list type="bullet"> <item> <description> "ForumConfig": Retrieves forum configuration details and
        /// determines if thanks are allowed for the specified forum. </description> </item> <item> <description>
        /// "TopicSummary": Generates a summary of thanks for a specific topic and reply, including whether the current
        /// user has thanked the post. </description> </item> <item> <description> "Profile": Displays the count of
        /// thanks received and given by a specific user. </description> </item> <item> <description> "EnableButton":
        /// Checks if the "FORUM_THANKS" table exists in the database. </description> </item> <item> <description>
        /// "MenuItem": Determines whether the "Thanks" menu item should be displayed based on configuration settings.
        /// </description> </item> <item> <description> "Admin": Renders the admin view for managing the component.
        /// </description> </item> If the <paramref name="template"> does not match any of the supported templates, an
        /// empty view is returned.</remarks>
        /// <param name="template">The name of the view component template to render. Supported templates include "ForumConfig",
        /// "TopicSummary", "Profile", "EnableButton", "MenuItem", and "Admin".</param>
        /// <param name="id">An optional identifier used by certain templates, such as "ForumConfig", "TopicSummary", and "Profile".
        /// Defaults to 0 if not provided.</param>
        /// <param name="topicid">An optional topic identifier used by the "TopicSummary" template. Defaults to 0 if not provided.</param>
        /// <param name="showcount">A boolean value indicating whether to display the count of thanks in the "TopicSummary" template. Defaults
        /// to <see langword="false"/>.</param>
        /// <param name="archived">A boolean value indicating whether to consider archived posts in the "TopicSummary" template. Defaults to
        /// <see langword="false"/>.</param>
        /// <param name="showlink">An optional boolean value indicating whether to display a link in the "TopicSummary" template. Defaults to
        /// <see langword="true"/>.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains an <see
        /// cref="IViewComponentResult"/> representing the rendered view component.</returns>
        public async Task<IViewComponentResult> InvokeAsync(string template,int? id = 0,int? topicid = 0, bool showcount = false, bool archived = false, bool? showlink = true)
        {
            if (template == "ForumConfig")
            {
                var forum = _dbContext.Forums
                .FromSqlInterpolated($"SELECT * FROM FORUM_FORUM WHERE F_ALLOWTHANKS=1")
                .SingleOrDefault(f => f.Id == id);
                ViewBag.IsAllowed = forum != null;
                ViewBag.ForumId = id;
                return await Task.FromResult((IViewComponentResult)View(template,forum));
            }
            if (template == "TopicSummary" && topicid != null && id != null)
            {
                var vm = new PostThanksViewModel
                {
                    UserId = _memberService.Current().Id,
                    TopicId = topicid.Value,
                    ReplyId = id.Value,
                    Thanked = false,
                    ShowCount = showcount,
                    Showlink = showlink != null ? showlink.Value : true,
                };
                vm.Thanked = thanksRepository.IsThanked(topicid.Value, id.Value,_memberService.Current()?.Id);
                vm.ThanksCount = thanksRepository.Count(topicid.Value, id.Value);
                vm.PostAuthor = thanksRepository.IsAuthor(topicid.Value, id.Value, archived);
                return await Task.FromResult((IViewComponentResult)View(template,vm));
            }
            if(template == "Profile")
            {
                var vm = new PostThanksProfile
                {
                    Received = thanksRepository.MemberCountReceived(id.Value),
                    Given = thanksRepository.MemberCountGiven(id.Value),
                };

                return await Task.FromResult((IViewComponentResult)View(template,vm));
            }
            if (template == "EnableButton")
            {
                var installed = _config.TableExists("FORUM_THANKS");
                return await Task.FromResult((IViewComponentResult)View(template,installed));
            }
            if (template == "MenuItem")
            {
                var showthanks = _config.TableExists("FORUM_THANKS") && _config.GetIntValue("STRTHANKS") == 1;

                return await Task.FromResult((IViewComponentResult)View(template,showthanks));
            }

            if (template == "Admin")
            {
                return await Task.FromResult((IViewComponentResult)View(template));
            }
            return await Task.FromResult((IViewComponentResult)View());
        }

    }
}

Snitz.PostThanks/Views/Shared/Components/PostThanks/Admin.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using System.Drawing.Text


    <div class="accordion-item">
        <h2 class="accordion-header" id="thanks-heading">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#thanks-collapse" aria-expanded="false" aria-controls="thanks-collapse">
                Post Thanks
            </button>
        </h2>
         <div id="thanks-collapse" class="accordion-collapse collapse" aria-labelledby="thanks-heading" data-bs-parent="#plugin-accordion">
            <div class="accordion-body">
                <form id="thanks-enable" asp-action="SaveFeatures" asp-controller="SnitzConfig" method="POST" data-ajax="true" data-ajax-update="#result">
                    @await Component.InvokeAsync("PostThanks", new {template="EnableButton"})
                </form> 
                <div id="result"></div>
            </div>
        </div>
    </div>

Snitz.PostThanks/Views/Shared/Components/PostThanks/EnableButton.cshtml
@model bool
@if (Model)
{
    <form asp-action="SaveSettings" asp-controller="SnitzConfig" method="POST" data-ajax="true" data-ajax-update="#thanks-result" >

    <div class="form-check form-switch mb-3">
        <input type="checkbox" role="switch" name="STRTHANKS" id="STRTHANKS" value="1" class="form-check-input" checked="@(SnitzConfig.IsEnabled("STRTHANKS"))" style="transform: scale(1.4);">
        <input type="checkbox" name="STRTHANKS" value="0" checked="" style="display: none">
        <label class="form-check-label" for="STRTHANKS">Enable Post Thanks</label>
    </div>
    </form>
    <div id="thanks-result"></div>
}

<storecontent asp-key="forum-plugins">
    <script>
        $(document).on("click",
            "#STRTHANKS",
            function() {
                $(this).closest("form").submit();
            });
    </script>
</storecontent>

Snitz.PostThanks/Views/Shared/Components/PostThanks/ForumConfig.cshtml
@model Forum?
@if (SnitzConfig.IsEnabled("STRTHANKS")){
    <div class="mb-3 bg-plugin text-bg-plugin p-3 rounded">
        <div class="panel">
            <div class="panel-heading">@Localizer["ForumSettingTitle"]<hr /></div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="strThanks" class="control-label col-xs-6">
                        <input id="strThanks" type="checkbox" name="strThanks" data-size="mini" data-id="@ViewBag.ForumId" checked="@ViewBag.IsAllowed" />
                        @Localizer["ForumSetting"]
                    </label>
                </div>
            </div>
        </div>
    </div>
    <storecontent asp-key="forum-plugins">
        <script>
            $(document)
                .ready(function () {

                    $('#strThanks').change(function () {
                        var id = $(this).data('id');
                        $.ajax(
                            {
                                url: SnitzVars.baseUrl + '/PostThanks/ForumSettings/' + id + '?check=' + this.checked,
                                async: false,
                                success: function (response) {
                                    //alert('saved');
                                },
                                error: function (jqXHR, textStatus, errorThrown) {
                                    appendAlert(errorThrown, 'warning');

                                }
                            });
                    });

                });
        </script>
    </storecontent>
}

Snitz.PostThanks/Views/Shared/Components/PostThanks/Profile.cshtml
@model PostThanks.Models.PostThanksProfile
<div class="card panel-secondary card-body mt-3">
    <h5 class="card-header"><i class="fa-regular fa-heart"></i> @Localizer["ForumSettingTitle"]</h5>
    <div class="card-body p-3">
        <label>@Localizer["lblReceived"] <span class="badge rounded-pill bg-success" title="@Localizer["lblReceived"] @Localizer["thanks"]" data-toggle="tooltip">@Model.Received</span> @Localizer["thanks"]</label><br />
        <label>@Localizer["given"] <span class="badge rounded-pill bg-primary" title="@Localizer["given"]" data-toggle="tooltip">@Model.Given</span></label>

    </div>
</div>

Snitz.PostThanks/Views/Shared/Components/PostThanks/TopicSummary.cshtml
@model PostThanks.Models.PostThanksViewModel
<span>
    @if (User.Identity.IsAuthenticated && Model.Showlink)
    {
        if (!Model.PostAuthor)
        {
            if (!Model.Thanked)
            {
                <i class="fa-regular fa-heart topic thumbs-up" title="@Localizer["Thank"]" data-id="@Model.TopicId" data-replyid="@Model.ReplyId" data-archived="@Model.IsArchived" data-toggle="tooltip"></i>
            }
            else
            {
                <i class="fa fa-heart topic position-relative z-1 thumbs-down" title="@Localizer["UnThank"]" data-id="@Model.TopicId" data-replyid="@Model.ReplyId" data-archived="@Model.IsArchived" data-toggle="tooltip">
                    @*             @if (Model.ShowCount && Model.ThanksCount > 0)
                    {
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger z-n1 thanks-list fs-6" data-placement="auto" data-id="@Model.TopicId" data-replyid="@Model.ReplyId">@Model.ThanksCount<span class="visually-hidden">unread messages</span></span>
                    } *@
                </i>
            }
        }

    }
    else
    {
        if (Model.ShowCount && Model.ThanksCount > 0)
        {
            <span class="badge rounded-pill bg-danger fs-6 thanks-list" data-placement="auto" data-id="@Model.TopicId" data-replyid="@Model.ReplyId">@Model.ThanksCount<span class="visually-hidden">unread messages</span></span>
        }
    }
</span>