SnitzCore.Admin/Controllers/FileManagerController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Primitives;
using SnitzCore.Data;
using SnitzCore.Data.Extensions;
using SnitzCore.Data.Models;
using System.Net.Mime;
using YG.ASPNetCore.FileManager.CommandsProcessor;
using YG.ASPNetCore.FileManager.Enums;

namespace SnitzCore.BackOffice.Controllers
{
    public class FileManagerController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly SnitzDbContext _dbcontext;
        private readonly IFileManagerCommandsProcessor _processor;

        public FileManagerController(IWebHostEnvironment env, SnitzDbContext dbcontext,IFileManagerCommandsProcessor processor)
        {
            _env = env;
            _dbcontext = dbcontext;
            _processor = processor;
        }

        [HttpPost, HttpGet]
        public async Task<IActionResult> SnitzFileApi(string id, Command command, string parameters, IFormFile file)
        {
            return await _processor.ProcessCommandAsync(id, command, parameters, file);
        }

        public IActionResult Index(string path = "")
        {
            return View();
        }

        [Route("Releases/")]
        public IActionResult Releases()
        {
            var rootpath = Path.Combine(_env.WebRootPath, "releases");
            if (!Directory.Exists(rootpath))
            {
                ViewBag.Error = "Uploads directory does not exist";
                return View("Error");
            }
            var dir = new DirectoryInfo(rootpath);
            var vm = new List<FileRelease>();

            foreach (var file in dir.GetFiles())
            {

                var filerec = _dbcontext.Database.SqlQuery<FileCount>($"SELECT [FC_ID],[Title],[FileName],[LinkHits],[LinkOrder],[Posted], [Archived],[Version],[ReadMe] FROM [FORUM_FILECOUNT] WHERE [FileName] = {file.Name}").ToList();
                if (filerec != null && filerec.Count == 1)
                {
                    vm.Add(new FileRelease
                    {
                        Id = filerec.First().Id,
                        Title = filerec.First().Title,
                        Filename = filerec.First().FileName,
                        LinkHits = filerec.First().LinkHits,
                        LinkOrder = filerec.First().LinkOrder,
                        Archived = filerec.First().Archived,
                        Posted = filerec.First().Posted,
                        Version = filerec.First().Version,
                        File = file,
                        ReadMe = filerec.First().ReadMe
                    });

                }
            }

            return View(vm);
        }

        public FileResult Download(int id)
        {
            var rootpath = Path.Combine(_env.WebRootPath, "releases");

            var file = _dbcontext.Database.SqlQuery<FileCount>($"SELECT * FROM FORUM_FILECOUNT WHERE FC_ID = {id}").Single();
            //update the counter
            string sql = $"UPDATE FORUM_FILECOUNT SET LinkHits = LinkHits + 1 WHERE FC_ID = {id}";
            _dbcontext.Database.ExecuteSqlRaw(sql);
            string virtualPath = "~/releases/" + file.FileName;

            return File(virtualPath, "application/zip", file.FileName);
        }
        [HttpPost]
        [RequestSizeLimit(52428800*4)]
        public IActionResult UploadRelease(IFormCollection form) 
        {
            if (StringValues.IsNullOrEmpty(form["Title"]) || form.Files.Count == 0)
            {
                return View("Error");
            }
            var rootpath = Path.Combine(_env.WebRootPath, "releases");
            for (int i = 0; i < form.Files.Count; i++)
            {
                IFormFile file = form.Files[i]; //Uploaded file 
                if (file != null)
                {
                    ContentDisposition contentDisposition = new ContentDisposition(file.ContentDisposition);
                    string? filename = contentDisposition.FileName;
                    var filepath = Path.Combine(rootpath,filename);

                    using (FileStream output = System.IO.File.Create(filepath))
                    { file.CopyTo(output); }

                    string title = form["Title"];
                    string version = form["Version"];

                    // Insert data using raw SQL
                    string sql = "INSERT INTO FORUM_FILECOUNT (FileName, Title,Version, Posted, LinkHits, LinkOrder,Archived) VALUES (@p0, @p1,@p2, @p3,@p4, @p5,@p6)";
                    _dbcontext.Database.ExecuteSqlRaw(sql, filename, title,version,DateTime.UtcNow.ToForumDateStr(),0,0,0);

                }
            }

            return RedirectToAction(nameof(Releases));
        }

        public IActionResult EditRelease(int id)
        {
            var filerec = _dbcontext.Database.SqlQuery<FileCount>($"SELECT [FC_ID],[Title],[FileName],[LinkHits],[LinkOrder],[Posted], [Archived],[Version],[ReadMe] FROM [FORUM_FILECOUNT] WHERE [FC_ID] = {id}").ToList();

            return PartialView("_EditForm",filerec.FirstOrDefault());
        }
        [HttpPost]
        public IActionResult EditRelease(FileCount model)
        {
            if (ModelState.IsValid)
            {
                string sql = "UPDATE FORUM_FILECOUNT SET Title = @p0, Version = @p1, LinkOrder = @p2, Archived = @p3 WHERE FC_ID = @p4";
                _dbcontext.Database.ExecuteSqlRaw(sql, model.Title, model.Version, model.LinkOrder, model.Archived, model.Id);
                return RedirectToAction(nameof(Releases));
            }
            return View("Error");
        }
    }

    public class FileViewModel
    {
        public FileInfo[] File {get;set; }
        public string Title {get;set;}

    }
    public class FileRelease
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Filename { get; set; }
        public int LinkHits { get; set; } = 0;
        public int LinkOrder { get; set; } = 0;
        public int Archived { get; set; } = 0;
        public string Posted { get; set; }
        public string Version {get;set;}
        public FileInfo File { get; set; }

        public string? ReadMe {get;set;}

    }
}

SnitzCore.Admin/Views/FileManager/Index.cshtml
@using System.IO
@using Microsoft.AspNetCore.Hosting
@using SnitzCore.BackOffice.Controllers
@using SnitzCore.Service.Extensions
@using YG.ASPNetCore.FileManager
@using YG.ASPNetCore.FileManager.Enums
@using YG.ASPNetCore.FileManager.ViewComponentsModel
@using YG.ASPNetCore.FileManager.ViewComponentsModel.LanguageModels
@using YG.ASPNetCore.FileManager.ViewComponentsModel.LanguageModels.BuiltIn
@inject IWebHostEnvironment _environment

@{
    Layout = "_MasterLayout";

}
@section Styles {
@this.RenderYGfilemanagerCss(false,new[]{"fontawesome"},Context.Request.PathBase)
<style>
    .yg-fm-fsitems.list .fsitem{
        width:99%;
    }
</style>
}

<div style="height: 600px; margin-bottom:20px" class="mt-3">
        @await Component.InvokeAsync("FileManagerComponent", new FileManagerModel(){
            Id = "FM1",
            RootFolder = _environment.ContentRootPath,
            ApiEndPoint = Url.Action("SnitzFileApi"),
            Config = new FileManagerConfig(){
                StorageMaxSizeMByte = 0,
                UseEncryption = false,
                UseRecycleBin = false,
                EncryptionKey = "<Your Super Secret Encryption Key>",
                DisabledFunctions = { Command.Zip, Command.Unzip },
                HiddenFolders = {"ar","ro","no-NB", "Controllers","bin", "runtimes", "Properties","refs", "_content", "codemirror", "Identity", "is-cache"},
                //Language = new TurkishLanguage(),                
            }
        })
</div>

@section Scripts{
    @this.RenderYGfilemanagerJavaScripts(new[]{"fontawesome.min.js"})
}

SnitzCore.Admin/Views/FileManager/Releases.cshtml
@using SnitzCore.BackOffice.Controllers
@using SnitzCore.Service.Extensions
@model List<FileRelease>

@{
    Layout = "Layout";
}
@section Styles{
    <style>
        .counter {
            margin-top: 5px;
            font-size: 14px;
            color: #555;
        }
        .counter.warning {
            color: red;
        }
        tbody td{
            border:none;
        }
        tbody:nth-child(odd) td {
            background-color: #ececec !important;
        }
    </style>
}
@if(User.IsInRole("SuperAdmin"))
{
    <div class="accordion  mb-3" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Upload New Release
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
                <form asp-controller="FileManager" asp-action="UploadRelease" method="post" enctype="multipart/form-data" class="needs-validation col-md-6" novalidate>
                        <div class="mb-3">
                            <label for="version" class="form-label">Version</label>
                            <input name="Version" id="version" class="form-control" placeholder="Version" required maxlength="10" />
                            <div class="invalid-feedback">
                                Please provide the version.
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="txtTitle" class="form-label">Description</label>
                            <textarea name="Title" id="txtTitle" class="form-control" placeholder="Title (required)" required maxlength="255" rows="2"></textarea>
                            <div id="charCounter" class="counter">0 / 255 characters</div>
                            <div class="invalid-feedback">
                                Please provide a Title.
                            </div>
                        </div>
                        <div class="mb-3">
                            <input type="file" placeholder="read me file" name="Files" class="form-control" accept=".md,.html,.txt" aria-describedby="radio1HelpBlock" />
                            @* <button type="submit" class="btn btn-success">Upload</button> *@
                            <span id="radio1HelpBlock" class="form-text text-muted">Select a read me file for this release.</span>
                        </div>

                        <div class="input-group mb-3">
                            <input type="file" name="Files" class="form-control" accept=".zip" required />
                            <button type="submit" class="btn btn-success">Upload</button>
                            <div class="invalid-feedback">
                                Please select a File.
                            </div>
                        </div>
                </form>
            </div>
        </div>
      </div>
    </div>
}

<div class="container">
    <h2>Forum Releases</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope ="col">Name</th>
                <th scope="col">Size (KB)</th>
                <th scope="col">Last Modified</th>
                <th scope="col">Ver.</th>
                <th scope="col">Downloads</th>
                <th scope="col">Readme</th>
                <th scope="col">&nbsp;</th>
            </tr>
        </thead>
        @foreach (var file in Model.OrderBy(f=>f.LinkOrder))
        {
            <tbody class="border-1 rounded">
                <tr>
                    <td>@file.Filename</td>
                    <td>@(file.File.Length / 1024)</td>
                    <td>@file.File.LastWriteTime.ToForumDisplay(SnitzConfig,SnitzCookie)</td>
                    <td>@file.Version</td>
                    <td>@file.LinkHits</td>
                    <td>Readme link @file.ReadMe</td>
                    <td class="fs-5">
                        <a data-toggle="tooltip" rel="nofollow" title="Download the file @file.Filename" href="@Url.Action("Download", "FileManager", new { id = file.Id })" class="text-decoration-none"><i class="fa fa-download"></i></a>
                        <a snitz-if="@(User.IsInRole("SuperAdmin"))" rel="nofollow" title="Edit file options" href="@Url.Action("EditRelease", "FileManager", new { id = file.Id })" class="text-decoration-none"><i class="fa fa-cog" data-id="@file.Id"></i></a>
                    </td>
                </tr>
                <tr>
                    <td colspan="7">@file.Title</td>
                </tr>
            </tbody>
        }
        @if (Model.Count == 0)
        {
            <tbody>
                <tr><td colspan="7" class="text-center"><h2>No current releases</h2></td></tr>
            </tbody>
        }
    </table>
    <p>
        If you wish to build/customise the application yourself, the source code is available on  <a href="https://github.com/huwred/Snitz.NetCore" title="Snitz .NET Core GitHub repository" target="_blank">GitHub</a>
    </p>
</div>
<modal id="fileModal" title="Edit Properties" >
    <modal-body>
        <div id="fileModal-body"></div>
    </modal-body>
    <modal-footer dismiss-text="Cancel">
        <button id="update-file" form="file-form" type="submit" class="btn btn-success">@Localizer["btnSave"]</button>
        <button type="reset" form="file-form" class="btn btn-warning ">@Localizer["btnReset"]</button>
    </modal-footer>
</modal>

@section Scripts{
<script>
        $(document).on("click",'.fa-cog',function(e){
            e.preventDefault();
            $('#fileModal-body').load(SnitzVars.baseUrl + "/FileManager/EditRelease/" + $(this).data("id"),function() {
                    $('#fileModal').modal('show');
                    ValidateForms();
            });
              
    });
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms,
    function (form) {
    form.addEventListener('submit',
        function (event) {
        if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
        }

        form.classList.add('was-validated');
        },false);
    });

    // Select the textarea and counter elements
    const textArea = document.getElementById('txtTitle');
    const charCounter = document.getElementById('charCounter');

    // Maximum character limit
    const maxChars = parseInt(textArea.getAttribute('maxlength'), 10);

    // Update the character counter as the user types
    textArea.addEventListener('input', () => {
        const currentLength = textArea.value.length;

        // Update the counter text
        charCounter.textContent = `${currentLength} / ${maxChars} characters`;

        // Add a warning class if near the limit
        if (currentLength > maxChars * 0.9) {
            charCounter.classList.add('warning');
        } else {
            charCounter.classList.remove('warning');
        }
    });

        function filedone() {
            $('#fileModal').modal('hide');
            location.href = SnitzVars.baseUrl + "/Releases";
        }
</script>
}

SnitzCore.Admin/Views/FileManager/_EditForm.cshtml
@model FileCount
<form asp-controller="FileManager" asp-action="EditRelease" id="file-form" class="needs-validation" novalidate data-ajax="true" data-ajax-complete="filedone">
    <div class="mb-3">
        <label asp-for="Title" class="form-label">Description</label>
        <textarea asp-for="Title" class="form-control" placeholder="Title (required)" required maxlength="255" rows="5"></textarea>
        <div class="invalid-feedback">
            Please provide a Title.
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="Version" class="form-label">Version</label>
        <input asp-for="Version" class="form-control" placeholder="Version" required maxlength="10" />
        <div class="invalid-feedback">
            Please provide the version.
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="LinkHits" class="form-label">Download Counter</label>
        <input asp-for="LinkHits" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="LinkOrder" class="form-label">Order</label>
        <input asp-for="LinkOrder" class="form-control" />
    </div>
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="FileName" />
    <input type="hidden" asp-for="Posted" />

</form>